### ISSUE TITLE
objsize: use x->r for more detailed reporting

### ISSUE THREAD

**Issue by effbiae** [AquaQAnalytics/TorQ#8]
https://github.com/AquaQAnalytics/TorQ/blob/master/code/common/memusage.q

it could be useful for objsize x  to report total size of objects in x that have refcount>1 - ie. objects referred to by objs other than the 'root' object.  

q)objsize bigtable
100000000000
q)x:bigtable
q)objsize x
100000000000 shared with 100000000000

**Comment by jonnypress** [comment]
Hi Jack

When we first started doing this we ideally want to return a list of (object size; returnable size), where returnable size took into account reference counts (i.e. how much memory would be freed if you deleted this object).  However, there turned out to be quite a few complexities with -16! that made it unreliable.  In the end we just stuck with returning the size of the object, as I think objects with just one reference are the dominant use case for this (e.g. big tables in memory in RDBs etc.)

Thanks 

Jonny
